### ISSUE TITLE
Reproducing resulting model from DecoupledNet

### ISSUE THREAD

**Issue by xionluhnis** [HyeonwooNoh/DecoupledNet#4]
While trying to train DecoupledNet on my own dataset that targets a specific group of classes (mostly humans), I tried to retrain the network using the Full Annotation scripts, changed with my own dataset.
Since the results of segmentation with my retrained network were worse than those of DecoupledNet without specialized dataset, I tried to reproduce the DecoupledNet model using the VOC2012 dataset, i.e. using the [Full annotation scripts](https://github.com/HyeonwooNoh/DecoupledNet/tree/master/training/002_train_seg_Full_anno) as is.

I let it run for 17500 iterations and got results that are getting similar, but still pretty far in term of segmentation quality. See illustrations below with a segmentation on a test image of mine (soccer player). The heatmap represents the human segmentation.
- Result using original [Full Annotation DecoupledNet model](https://github.com/HyeonwooNoh/DecoupledNet/tree/master/model/DecoupledNet_Full_anno)
  ![original-voc](https://cloud.githubusercontent.com/assets/1904312/14999325/892ad46e-1156-11e6-8af7-91cea83837f8.png)
- Result after 17500 iterations retraining (Full annotation scripts / VOC 2012 dataset):
  ![retrained-voc](https://cloud.githubusercontent.com/assets/1904312/14999382/d62cc3e4-1156-11e6-93d0-edcc7f4b062d.png)

As you can see, there's a lot more noise, and it's far from being as smooth.
I thought: maybe it hasn't fully converged so I should just train more, so I finetuned for 17500 more iterations, but that didn't seem to improve.
- Result after 35000 iterations training:
  ![retrained-voc-35000](https://cloud.githubusercontent.com/assets/1904312/14999416/2bc821ae-1157-11e6-883a-a7b266203d56.png)

Did you do any further processing to reach the model you got or should I be able to get a similar model with the scripts you provided? Do you have any idea why my results would be so different?

I trained on a Titan X on Ubuntu 14.04 and the installation from caffe of DecoupledNet, without modification.

**Comment by williford** [comment]
@xionluhnis 

My impression is that sometimes the model gets stuck in a local minimum. It looks like I've trained it at least once and gotten a good result. I've trained it multiple times since then, but the results look worse. 

Can you try submitting your results to the PASCAL VOC server? Run the MATLAB code and then place the results in a directory "results/VOC2012/Segmentation/comp6_test_cls/", tar.gz it, and submit to http://host.robots.ox.ac.uk:8080/ (as mentioned in #1).

It might be an issue with the libraries that you use. What versions of CUDA and CUDNN (if applicable) are you using? When I've gotten bad results, I was using CUDA 6.5.14 and CUDNN 6.5.18.

**Comment by williford** [comment]
I have been able to train good models a couple of times now (overall seg accuracy of around 95% on the training weights - before running the BN inference). It seems that the results may depend on the libraries (CUDA, CUDNN, or blas), although I haven't ruled out that it is the result of randomly getting stuck in a local minimum.

**Comment by xionluhnis** [comment]
I am using CUDA 7.5.18 with CuDNN v1 (the other versions v2,v3,v4 are seemingly not compatible with the version of Caffe of DecoupledNet).

I will try to retrain and see how different my results get, and submit to the PASCAL VOC server.
What configuration did you use to get good results?

**Comment by williford** [comment]
CUDA 7.0 without CuDNN seems to reliably give good results.

**Comment by xionluhnis** [comment]
Thanks!
That was the issue. CuDNN seems to mess up something.

I tried Cuda 7.5 without CuDNN (just commented USE_CUDNN=1 in makefile), and now I got much better results!

![test](https://cloud.githubusercontent.com/assets/1904312/15476552/9b9b7d74-20dd-11e6-802f-219009a0d7c2.png)
